### PR TITLE
Simple Locale Switcher hu (magyar - Hungarian) translation

### PR DESCRIPTION
**Pull request by ovari**
https://github.com/nohamelin/simple-locale-switcher/issues/31

Converted multiple to single merge request.

### CODE REVIEW

**Comment by ovari** [comment]
Thank you @nohamelin for your message.

This is similar to:
Névjegyzék (CardBook) https://addons.thunderbird.net/hu/thunderbird/addon/cardbook/
Tömörített fejléc (CompactHeader) https://addons.thunderbird.net/hu/thunderbird/addon/compactheader/
Üzenet átirányítás (Mail Redirect) https://addons.thunderbird.net/hu/thunderbird/addon/mailredirect/
Thunderbird-összehangolás (TbSync) https://addons.thunderbird.net/hu/thunderbird/addon/tbsync/

Names of a "brand" can vary between locales (or countries). For example [Holden](https://www.holden.com.au/cars) and [Opel](https://www.opel.hu/gepjarmuvek/passenger-cars/passenger_cars.html) are different "brand" names for the same car. Sometimes the model is the same, for example "Astra", being a [Holden Astra](https://www.holden.com.au/cars/astra-hatch) or [Opel Astra](https://www.opel.hu/gepjarmuvek/opel_range/autok/astra-5-ajtos/index.html).

**Comment by ovari** [comment]
@nohamelin Are you able to accept the PR as is or do you need further action from us? Thank you

**Comment by ovari** [comment]
Are you able to accept the merge or do you need us to remove the readme? Thank you

**Comment by nohamelin** [comment]
I will do the remaining changes. Thanks.

**Comment by ovari** [comment]
Please advise when you have accepted so we can delete our fork of you add-on. Thank you

**Comment by ovari** [comment]
@nohamelin could you please advise the status of this pull request? Thank you

**Comment by ovari** [comment]
@nohamelin could you please advise when you can accept this pull request to enable us to delete our fork. Thank you

**Comment by ovari** [comment]
Thank you

**Comment by nohamelin** [comment]
Merged via 1e902a3.

**Pull request closed without merging**
