### PR TITLE
Added gd translation

### PR DESCRIPTION
**Pull request by gunchleoc**
New translation for Scottish Gaelic (gd). Please let me know if there is anything else that needs doing to add it.

### CODE REVIEW

**Comment by nohamelin** [comment]
Hi, 
Thanks for the translation. Some minor details:
* Please not use 'Mozilla' in a localized form in the preferences.dtd file. Brand names remains usually in English, [though it's a hot source of discussion] (https://groups.google.com/d/topic/mozilla.dev.l10n/tLT8O_UcJU8/discussion). Anyway, I'm seeing the official gd localization for Fx doesn't do it neither in the 'about Firefox' window.
* Use the first letter of each sentence for the accesskeys in the languages.dtd file.
* Can you do shorter (a bit, at least) the string **popup.restart.label** in overlay.dtd? It gets truncated when the toolbar button is placed in the main menu pane of Firefox:

sls-menu-gd


I will accept your pull request, but, please consider to registering as an user at [Babelzilla](https://www.babelzilla.org/index.php?option=com_wts&extension=5713&type=show) too, where I manage all the translations, and translators are notified of future updates. If you want to do of it a "just once time" contribution, that is ok too. And it remembers me that I should have added this type of info in the README of the project...

**Comment by gunchleoc** [comment]
Thanks for the review!

I can register on Babelzile, I am already on Babelzilla Beta - I had just overlooked your link.

So, you can ignore the pull request if you want and I'll patch things up on Babelzilla, so you won't have multiple workflows.

**Comment by gunchleoc** [comment]
OK, translation updated now - I have trouble logging in at Babelzilla, so I have contacted them. It would be more convenient for me as well to get notifications about updates.

I left out the "afterwards" bit in **popup.restart.label** - could you pease check again if it still truncates?

**Comment by nohamelin** [comment]
It's hard to ensure that the label will be not truncated, as it depends of the system of each user, but I think that it's fine now. 

I wil leave this pull request open until your babelzilla problem is solved. Thanks again for your work.

**Comment by gunchleoc** [comment]
I have managed to access BabelZilla now with their help. Their xpi-creating function is very neat, so I did some more proofreading over there. Please ignore this pull request now.

**Pull request closed without merging**
